const PREFIX = "PRODUCT";

export const GET_LIST_PRODUCTS = PREFIX + "GET_LIST_PRODUCT";
export const GET_LIST_PRODUCTS_SUCCESS = PREFIX + "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCTS_FAIL = PREFIX + "GET_LIST_PRODUCT_FAIL";

export const PAGE_CHANGE = PREFIX + "PAGE_CHANGE";
export const PAGE_SIZE_CHANGE = PREFIX + "PAGE_SIZE_CHANGE";
export const KEYWORD_CHANGE = PREFIX + "KEYWORD_CHANGE";
export const STATUS_CHANGE = PREFIX + "STATUS_CHANGE";
export const SORT_BY_TIME_CHANGE = PREFIX + "SORT_BY_TIME_CHANGE";
export const SORT_BY_TIME_RANGE_CHANGE = PREFIX + "SORT_BY_TIME_RANGE_CHANGE";
export const TIME_RANGE_CHANGE = PREFIX + "TIME_RANGE_CHANGE";

export const SHOW_TIME_RANGE_POPUP = PREFIX + "SHOW_TIME_RANGE_POPUP";
export const HIDE_TIME_RANGE_POPUP = PREFIX + "HIDE_TIME_RANGE_POPUP";
export const SHOW_PRODUCT_POPUP = PREFIX + "SHOW_PRODUCT_POPUP";
export const HIDE_PRODUCT_POPUP = PREFIX + "HIDE_PRODUCT_POPUP";
