const PREFIX = "PRODUCT";

export const GET_LIST_PRODUCTS = PREFIX + "GET_LIST_PRODUCT";
export const GET_LIST_PRODUCTS_SUCCESS = PREFIX + "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCTS_FAIL = PREFIX + "GET_LIST_PRODUCT_FAIL";

export const PAGE_CHANGE = PREFIX + "PAGE_CHANGE";
export const PAGE_SIZE_CHANGE = PREFIX + "PAGE_SIZE_CHANGE";
export const KEYWORD_CHANGE = PREFIX + "KEYWORD_CHANGE";
export const STATUS_CHANGE = PREFIX + "STATUS_CHANGE";
export const SORT_BY_CHANGE = PREFIX + "SORT_BY_CHANGE";
export const DATE_RANGE_CHANGE = PREFIX + "DATE_RANGE_CHANGE";

export const SHOW_TIME_RANGE_POPUP = PREFIX + "SHOW_TIME_RANGE_POPUP";
export const HIDE_TIME_RANGE_POPUP = PREFIX + "HIDE_TIME_RANGE_POPUP";
export const SHOW_PRODUCT_POPUP = PREFIX + "SHOW_PRODUCT_POPUP";
export const HIDE_PRODUCT_POPUP = PREFIX + "HIDE_PRODUCT_POPUP";

//popup
export const GET_MACHINES = PREFIX + "GET_MACHINES";
export const GET_MACHINES_SUCCESS = PREFIX + "GET_MACHINES_SUCCESS";
export const GET_MACHINES_FAIL = PREFIX + "GET_MACHINES_FAIL";
export const SKU_SELECT = PREFIX + "SKU_SELECT";
export const POPUP_KEYWORD_CHANGE = PREFIX + "POPUP_KEYWORD_CHANGE";
export const GET_LINE_ITEMS_BY_SKU = PREFIX + "GET_LINE_ITEMS_BY_SKU";
export const GET_LINE_ITEMS_BY_SKU_SUCCESS = PREFIX + "GET_LINE_ITEMS_BY_SKU_SUCCESS";
export const GET_LINE_ITEMS_BY_SKU_FAIL = PREFIX + "GET_LINE_ITEMS_BY_SKU_FAIL";
export const POPUP_STATUS_CHANGE = PREFIX + "POPUP_STATUS_CHANGE";
export const POPUP_MACHINE_CHANGE = PREFIX + "POPUP_MACHINE_CHANGE";
export const POPUP_PROCESS_TIME_CHANGE = PREFIX + "POPUP_PROCESS_TIME_CHANGE";

export const UPDATE_LINE_ITEM_STATUS = PREFIX + "UPDATE_LINE_ITEM_STATUS";
export const UPDATE_LINE_ITEM_STATUS_SUCCESS = PREFIX + "UPDATE_LINE_ITEM_STATUS_SUCCESS";
export const UPDATE_LINE_ITEM_STATUS_FAIL = PREFIX + "UPDATE_LINE_ITEM_STATUS_FAIL";
