const PREFIX = "ORDER";

export const GET_LIST_ORDERS = PREFIX + "GET_LIST_ORDERS";
export const GET_LIST_ORDERS_SUCCESS = PREFIX + "GET_LIST_ORDERS_SUCCESS";
export const GET_LIST_ORDERS_FAIL = PREFIX + "GET_LIST_ORDERS_FAIL";

export const PAGE_CHANGE = PREFIX + "PAGE_CHANGE";
export const PAGE_SIZE_CHANGE = PREFIX + "PAGE_SIZE_CHANGE";
export const KEYWORD_CHANGE = PREFIX + "KEYWORD_CHANGE";
export const STATUS_CHANGE = PREFIX + "STATUS_CHANGE";
export const SORT_BY_CHANGE = PREFIX + "SORT_BY_CHANGE";
export const DATE_RANGE_CHANGE = PREFIX + "DATE_RANGE_CHANGE";

//popup
export const SHOW_DATE_RANGE_POPUP = PREFIX + "SHOW_DATE_RANGE_POPUP";
export const HIDE_DATE_RANGE_POPUP = PREFIX + "HIDE_DATE_RANGE_POPUP";