import mongoose, {Schema} from "mongoose";

const FulfillmentSchema = mongoose.Schema({
    created_at:                   Date,
    id:                           Number,
    order_id:                     Number,
    receipt:                      String,
    status:                       String,
    tracking_company:             String,
    tracking_company_code:        String,
    tracking_numbers:             [String],
    tracking_number:              String,
    tracking_url:                 String,
    tracking_urls:                [String],
    updated_at:                   Date,
    province:                     String,
    province_code:                String,
    district:                     String,
    district_code:                String,
    ward:                         String,
    ward_code:                    String,
    cod_amount:                   Number,
    carrier_status_name:          String,
    carrier_cod_status_name:      String,
    carrier_status_code:          String,
    carrier_cod_status_code:      String,
    location_id:                  Number,
    location_name:                String,
    note:                         String,
    carrier_service_package_name: String,
    coupon_code:                  String,
    ready_to_pick_date:           Date,
    picking_date:                 String,
    delivering_date:              String,
    delivered_date:               String,
    return_date:                  String,
    not_meet_customer_date:       String,
    waiting_for_return_date:      String,
    cod_paid_date:                String,
    cod_receipt_date:             String,
    cod_pending_date:             String,
    cod_not_receipt_date:         String,
    cancel_date:                  String,
    is_view_before:               String,
    country:                      String,
    country_code:                 String,
    zip_code:                     String,
    city:                         String,
    real_shipping_fee:            Number,
    shipping_notes:               String,
    total_weight:                 Number,
    package_length:               Number,
    package_width:                Number,
    package_height:               Number,
    boxme_servicecode:            String,
    transport_type:               Number,
    address:                      String,
    sender_phone:                 String,
    sender_name:                  String,
    carrier_service_code:         String,
    from_longtitude:              Number,
    from_latitude:                Number,
    to_longtitude:                Number,
    to_latitude:                  Number,
    sort_code:                    String,
    is_drop_off:                  Boolean,
    is_insurance:                 Boolean,
    insurance_price:              Number,
    is_open_box:                  Boolean,
    request_id:                   String,
    carrier_options:              String,
    note_attributes:              String,
    first_name:                   String,
    last_name:                    String,
    shipping_address:             String,
    shipping_phone:               String,
    line_items:       [Schema.Types.ObjectId],
});

const Fulfillment = mongoose.model('Fulfillment', FulfillmentSchema);

export default Fulfillment;